---

- hosts: localhost
  connection: local
  roles:
    - dev
    - exercism
    - flatpak
    - gnome-shell
    - javascript
    - kubernetes
    - latex
    - minecraft
    - music
    - podman
    - ruby
    - system
    - vim
