---

- name: Ensure some base directories are present
  file: path={{ ansible_env.HOME }}/{{ item }} state=directory
  with_items:
    - Projects
    - Projects/gocode
    - Projects/stackoverflow
    - Pictures/Wallpaper
    - Software

- name: Set bashrc
  template: src=bashrc.j2 dest={{ ansible_env.HOME }}/.bashrc

- name: Set bash_profile
  template: src=bash_profile.j2 dest={{ ansible_env.HOME }}/.bash_profile

- name: Set git config
  template: src=gitconfig.j2 dest={{ ansible_env.HOME }}/.gitconfig

- name: Set tmux config
  template: src=tmux.conf.j2 dest={{ ansible_env.HOME }}/.tmux.conf
