---

- name: Load gnome-shell specific packages
  include_vars: "gnome-shell-config.yml"

- name: Add gnome templates
  copy: src=gnome/Templates/ dest={{ ansible_env.HOME }}/Templates/

- name: Set default applications for gnome files
  template: src=gnome/default-applications.list.j2 dest={{ ansible_env.HOME }}/.local/share/applications/defaults.list

- name: Ensure Screenshot directory is present
  file: path={{ ansible_env.HOME }}/Pictures/Screenshots/ state=directory

# Note: should be preinstalled so no action needed
#- name: Ensure gnome-settings is present
#  dnf: name={{item}} state=latest

- name: Set gnome specific configurations
  command: 'gsettings set "{{ item.path }}" "{{ item.key }}" "{{ item.value }}"'
  with_items: "{{ gnome_configurations }}"

