---

- name: Load OS specific packages
  include_vars: "packages-{{ ansible_os_family }}.yml"

- name: Load OS specific development packages
  include_vars: "packages-dev-{{ ansible_os_family }}.yml"

- name: Add yum/dnf repos
  template: src=dnf/{{ item }}.repo.j2 dest=/etc/yum.repos.d/{{ item }}.repo
  become: yes
  with_items:
    - 'google-chrome'

- name: Install packages
  dnf: name={{item}} state=latest
  become: yes
  with_flattened:
    - development_packages
    - system_packages
    - application_packages
