---

development_packages:
  - git
  - kdiff3
  - tmux
  - tmuxinator
  - openssh
  - the_silver_searcher
  - pandoc
  - podman
  - docker
  - docker-selinux
  - golang
  - ctags
  - graphviz
  - plantuml
  - jq
  - fzf

