---

- name: Install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.8.0/bin/linux/amd64/kubectl
    dest: "{{ ansible_env.HOME }}/bin/kubectl"
    mode: 0755
