---

# - name: Setup minikube
#   import_tasks: minikube.yml
#   tags: ['minikube']

# - name: Setup latest kubectl
#   import_tasks: kubectl.yml
#   tags: ['dev', 'kubernetes', 'k8s']

- name: Install k8s client
  become: yes
  dnf:
    name: kubernetes-client
    state: latest
