---

- name: Set Exercism version
  set_fact:
    exercism_version: 'v3.0.13'

- name: Download exercism CLI
  get_url:
    url: "https://github.com/exercism/cli/releases/download/{{ exercism_version }}/exercism-linux-64bit.tgz"
    dest: "/tmp/exercism.tar.gz"

- name: Extract exercism CLI
  get_url:
    src: "/tmp/exercism.tar.gz"
    dest: "/tmp/exercism"
