---

packages:
  - ruby
  - ruby-devel
  - rubygems
  - gcc
  - gcc-c++
  - bzip2
  - openssl-devel
  - libyaml-devel
  - libffi-devel
  - gdbm-devel
  - ncurses-devel
  - readline-devel
  - zlib-devel

ruby_gems:
  - airstream
  - mailcatcher
  - git_remote_branch
  - brakeman
  - rubocop
  - rspec
  - guard
  - rails

