---

- name: Load ruby gems to install
  include_vars: "packages.yml"

- name: Install ruby dependencies
  become: yes
  dnf: name={{ query('flattened', ['{{ packages }}']) }} state=present

# - name: Install ruby gems
#   gem: name={{ query('flattened', ['{{ ruby_gems }}']) }} state=latest
