---

- name: Load ruby gems to install
  include_vars: "packages.yml"

- name: Install ruby dependencies
  become: yes
  dnf: name={{ item }} state=present
  with_flattened:
    - "{{ packages }}"

#- name: Install ruby gems
  #gem: name={{ item }} state=latest
  #with_flattened:
    #- "{{ ruby_gems }}"
